# Generated by Django 3.2.12 on 2023-08-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField()),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=50)),
                ('precioVenta', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('tienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionTienda.tienda')),
            ],
        ),
    ]
