# Generated by Django 3.2.12 on 2023-08-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='fechaCreacion',
            field=models.DateField(auto_now=True),
        ),
    ]
