# Generated by Django 3.2.12 on 2023-08-04 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTienda', '0002_alter_tienda_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestionTienda.tienda'),
        ),
    ]
